FROM python:3.10-slim

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY keys ./keys
COPY data ./data

# Expose the api port
EXPOSE 8000

# Run the api
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]