services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: juris-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../chroma_db:/app/chroma_db
      - ../keys:/app/keys:ro # mounts json on container

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - api

volumes: 
  hf-cache:
  grafana_data:

networks:
  default:
    driver: bridge