name: CI/CD - Deploy Juris API to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Decode service account key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ${{ github.workspace }}/gcp-key.json

    - name: Configure gcloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/juris-api/juris-api:latest -f infra/Dockerfile.api .

    - name: Push Docker image to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/juris-api/juris-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy juris-api \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/juris-api/juris-api:latest \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port=8000 \
          --memory=1Gi \
          --timeout=600 \
          --set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account.json